name: Build and deploy to Azure

env:
  AZURE_WEBAPP_NAME: receptsamlingen
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  
on:
  push:
    branches: 
      - master

jobs:
  prepare:
    runs-on: windows-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
  build:
    runs-on: windows-latest
    needs: prepare
    steps:     
    - name: Restore NuGet packages
      run: nuget restore Receptsamlingen.sln
      
    - name: Build and publish Web App
      run: msbuild Receptsamlingen.sln /p:Configuration=Release /p:DeployOnBuild=true /p:OutDir=${{env.DOTNET_ROOT}}/receptsamlingen
 
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: published_webapp
        path: ${{env.DOTNET_ROOT}}/receptsamlingen

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:        
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: published_webapp
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
